# Generated by Django 4.2.10 on 2024-03-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=255, null=True)),
                ('operator_location', models.CharField(max_length=255, null=True)),
                ('operator_contact', models.CharField(max_length=255, null=True)),
                ('operator_email', models.EmailField(max_length=255, null=True)),
                ('operator_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255, null=True)),
                ('region_country', models.CharField(max_length=255, null=True)),
                ('region_contact', models.CharField(max_length=255, null=True)),
                ('region_contact_email', models.CharField(max_length=255, null=True)),
                ('region_contact_phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_name', models.CharField(max_length=255, null=True)),
                ('well_location', models.CharField(max_length=255, null=True)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('well_section', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('well_depth', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('well_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('well_activity', models.CharField(max_length=5000, null=True)),
                ('operator', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata.operator')),
            ],
        ),
    ]
