# Generated by Django 4.2.10 on 2024-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surface',
            name='pressure_bottom_hole',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='pressure_condensor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='pressure_seperator',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='required_output',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='temp_bottom_hole',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='turbine_efficiency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='turbine_exit_pressure',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='wellhead_number',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_depth',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_section',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
