# Generated by Django 4.2.10 on 2024-03-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_alter_surface_pressure_bottom_hole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surface',
            name='pressure_bottom_hole',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='pressure_condensor',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='pressure_seperator',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='required_output',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='temp_bottom_hole',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='turbine_efficiency',
        ),
        migrations.RemoveField(
            model_name='surface',
            name='turbine_exit_pressure',
        ),
        migrations.AlterField(
            model_name='surface',
            name='wellhead_number',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_depth',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_section',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
