# Generated by Django 4.2.10 on 2024-03-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_remove_surface_pressure_bottom_hole_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Surface',
        ),
    ]
