# Generated by Django 4.2.10 on 2024-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0006_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surface',
            name='pressure_bottom_hole',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='pressure_condensor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='pressure_seperator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='required_output',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='temp_bottom_hole',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='turbine_efficiency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='turbine_exit_pressure',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surface',
            name='wellhead_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
